# version: '3.9'

# services:
#   djangoapp:
#     container_name: djangoapp
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - PG_USER=postgres
#       - PG_PASSWORD=maquina123
#       - PG_DB=QuickFlight
#       - PG_HOST=db
#       - PG_PORT=5432
#     depends_on:
#       - db
#   db:
#     container_name: db
#     image: postgres:14
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=maquina123
#       - POSTGRES_DB=QuickFlight
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}



version: '3.9'


services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=maquina123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=QuickFlight

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '5173:5173'

    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

    depends_on:
      - backend

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=maquina123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=QuickFlight

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
