# Generated by Django 5.0 on 2023-12-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
